import {
  AlarmClock,
  ArrowRight,
  BatteryFull,
  Bell,
  BookOpen,
  CalendarArrowUp,
  CalendarCheck,
  CalendarClock,
  CalendarSearch,
  CalendarX,
  Check,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDashed,
  CircleDot,
  CircleHelp,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Copy,
  Database,
  Dices,
  Disc3,
  Download,
  Drama,
  Equal,
  Eye,
  EyeOff,
  ExternalLink,
  File,
  FileCheck2,
  FileDown,
  FileImage,
  FileOutput,
  FilePen,
  FileText,
  FileX,
  FlaskConical,
  Folder,
  FolderOpen,
  GitFork,
  Hammer,
  Hand,
  Handshake,
  History,
  House,
  Info,
  KeyRound,
  LayoutGrid,
  Link,
  List,
  ListChecks,
  ListOrdered,
  LoaderCircle,
  Lock,
  MessageSquareHeart,
  MessagesSquare,
  NotebookPen,
  Paperclip,
  PenLine,
  Pencil,
  PencilRuler,
  Plus,
  Presentation,
  RotateCcw,
  Scale,
  Search,
  Send,
  Settings2,
  Share2,
  Shield,
  Signal,
  SkipForward,
  Sparkles,
  Split,
  ThumbsUp,
  Ticket,
  Trash2,
  Upload,
  UserMinus,
  UserPlus,
  UserRound,
  UserSearch,
  UsersRound,
  WandSparkles,
  Wifi,
  X,
  type LucideIcon,
} from "lucide-react";

/**
 * 아이콘 레지스트리.
 *
 * 프로토타입이 lucide 를 kebab-case 이름으로 부르므로 그 어휘를 그대로 유지한다.
 * 라이브러리 전체를 import 하면 번들에 1000개가 넘는 아이콘이 들어오므로
 * **실제로 쓰는 아이콘만** 여기에 등록한다. 새 화면에서 아이콘이 필요하면
 * 위 import 와 아래 맵에 한 줄씩 추가하면 된다.
 */
const REGISTRY = {
  "alarm-clock": AlarmClock,
  "arrow-right": ArrowRight,
  "battery-full": BatteryFull,
  bell: Bell,
  "book-open": BookOpen,
  "calendar-arrow-up": CalendarArrowUp,
  "calendar-check": CalendarCheck,
  "calendar-clock": CalendarClock,
  "calendar-search": CalendarSearch,
  "calendar-x": CalendarX,
  check: Check,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  circle: Circle,
  "circle-alert": CircleAlert,
  "circle-check": CircleCheck,
  "circle-dashed": CircleDashed,
  "circle-dot": CircleDot,
  "circle-help": CircleHelp,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  clock: Clock,
  copy: Copy,
  database: Database,
  dices: Dices,
  "disc-3": Disc3,
  download: Download,
  drama: Drama,
  equal: Equal,
  eye: Eye,
  "eye-off": EyeOff,
  "external-link": ExternalLink,
  file: File,
  "file-check-2": FileCheck2,
  "file-down": FileDown,
  "file-image": FileImage,
  "file-output": FileOutput,
  "file-pen": FilePen,
  "file-text": FileText,
  "file-x": FileX,
  "flask-conical": FlaskConical,
  folder: Folder,
  "folder-open": FolderOpen,
  "git-fork": GitFork,
  hammer: Hammer,
  hand: Hand,
  handshake: Handshake,
  history: History,
  house: House,
  info: Info,
  "key-round": KeyRound,
  "layout-grid": LayoutGrid,
  link: Link,
  list: List,
  "list-checks": ListChecks,
  "list-ordered": ListOrdered,
  "loader-circle": LoaderCircle,
  lock: Lock,
  "message-square-heart": MessageSquareHeart,
  "messages-square": MessagesSquare,
  "notebook-pen": NotebookPen,
  paperclip: Paperclip,
  "pen-line": PenLine,
  pencil: Pencil,
  "pencil-ruler": PencilRuler,
  plus: Plus,
  presentation: Presentation,
  "rotate-ccw": RotateCcw,
  scale: Scale,
  search: Search,
  send: Send,
  "settings-2": Settings2,
  "share-2": Share2,
  shield: Shield,
  signal: Signal,
  "skip-forward": SkipForward,
  sparkles: Sparkles,
  split: Split,
  "thumbs-up": ThumbsUp,
  ticket: Ticket,
  "trash-2": Trash2,
  upload: Upload,
  "user-minus": UserMinus,
  "user-plus": UserPlus,
  "user-round": UserRound,
  "user-search": UserSearch,
  "users-round": UsersRound,
  "wand-sparkles": WandSparkles,
  wifi: Wifi,
  x: X,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof REGISTRY;

export type IconProps = {
  name: IconName;
  size?: number;
  strokeWidth?: number;
  className?: string;
};

export function Icon({ name, size = 20, strokeWidth = 2, className }: IconProps) {
  const Glyph = REGISTRY[name];
  return (
    <Glyph
      size={size}
      strokeWidth={strokeWidth}
      className={className}
      aria-hidden="true"
      style={{ flex: "0 0 auto" }}
    />
  );
}
